### 2D Points Pixel coordinates in images

$\textbf{x} =(x,y) \in \mathbb{R}^2$

<img src = 'pixel_coordinate.png' width = 500/>

## Coordenadas homogéneas

$\mathbf{\hat{x}} = (\hat{x},\hat{y},\hat{w}) \in P^2$

$\mathbf{\hat{x}} = (\hat{x},\hat{y},\hat{w}) = \hat{w}(x,y,1) = \hat{w}\bar{\mathbf{x}}$

In [84]:
import numpy as np
def euclidean2D_to_homogeneus(x):
    """
    Convert a 2D point in euclidean space to a projective space
    Parameters
    ----------
    x : np.Array
        Point in 2D euclidean space
    Returns
    -------
    x : np.Array
        Point in projective space
    """ 
    assert  (2 == len(x)), 'The argument is not a 2D Point'
    x = np.append(x,1)
    return x

def homogeneus_to_euclidean2D(x):
    """
    Convert a 2D point in projective space to euclidean space
    Parameters
    ----------
    x : np.Array
        Point in projective space
    Returns
    -------
    x : np.Array
        Point in 2D euclidean space
    """ 
    assert  (3 == len(x)), 'The argument is not a 3D Point'
    assert  (0 != x[2])  , 'x is a point in the infinite, it doesnt '
    x=x/x[2]
    x = np.delete(x,2)
    return x

    
    

In [76]:
x = np.array([3,4])
euclidean2D_to_homogeneus(x)

array([3, 4, 1])

In [85]:
x = np.array([3,4,2])
homogeneus_to_euclidean2D(x)

array([1.5, 2. ])

## Líneas

$ax+by+c = 0$

$\hat{l} = (a,b,c)$

$\bar{\mathbf{x}} \cdot \hat{l} = ax+by+c = 0$

$l = (\hat{n}_x,\hat{n}_y,d) = (\mathbf{\hat{n},d}), con ||\mathbf{\hat{n}}|| =1$

## Cruce de rectas usando coordenadas homogéneas

Piensa en:


$\hat{l}_1: 3x + 5y +2 = 0$

$\hat{l}_2:-4x+6y+1=0$

In [93]:
l1 = np.array([2,6,2])
l2 = np.array([-5,8,4])

In [94]:
x = np.cross(l1,l2)
homogeneus_to_euclidean2D(x)

array([ 0.17391304, -0.39130435])

## Recta que une dos puntos

In [102]:
x1 = np.array([-7,-4])
x2 = np.array([3,1])

In [103]:
x1 = euclidean2D_to_homogeneus(x1)
x2 = euclidean2D_to_homogeneus(x2)

In [104]:
np.cross(x1,x2)

array([-5, 10,  5])

## Puntos en 3D

$\textbf{x} =(x,y,z) \in \mathbb{R}^3$

$\mathbf{\hat{x}} = (\hat{x},\hat{y},\hat{x},\hat{w}) \in P^3$


## Planos

$\bar{\mathbf{x}} \cdot \hat{m}= ax+by+cz+d=0$